### ISSUE TITLE
[PE-D][Tester D] Illegal moves could be made by adjusting the game storage file

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T18-1/tp#123] opened 2023-11-03 16:24 UTC
The chessboard could be manipulated in a way where such moves should not be able to be done, such as the screenshot below, where the Rook should not be allowed in such position.

![image.png](https://raw.githubusercontent.com/lisizhuang-0121/ped/main/files/2d9648b7-f545-4458-8100-81b3ad732524.png)

The file could be loaded successfully into the gameplay.

![image.png](https://raw.githubusercontent.com/lisizhuang-0121/ped/main/files/d0ba6e16-98fc-41e9-a940-4fd94af543fd.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lisizhuang-0121/ped#2

**Comment by TongZhengHong** [comment] 2023-11-04 15:51
- Duplicate of #140

**Closed as completed** 2023-11-08 11:27 UTC
