### ISSUE TITLE
[PE-D][Tester D] Invalid commands are only handled as "move" command in the gameplay

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T18-1/tp#135] opened 2023-11-03 16:32 UTC
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
If an invalid command is entered during gameplay, there will only be error message mentioning "Unable to parse coordinate!" 

![image.png](https://raw.githubusercontent.com/lisizhuang-0121/ped/main/files/5a948b48-2b94-499b-9d5c-4b365d181695.png)

If possible, there could be better error messages as feedback to the user.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: lisizhuang-0121/ped#4

**Comment by TongZhengHong** [comment] 2023-11-04 15:06
- Duplicate of #120

**Closed as completed** 2023-11-06 01:07 UTC
