### ISSUE TITLE
[PE-D][Tester C] UG bug: The explanation is too brief 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T18-1/tp#139] opened 2023-11-03 16:33 UTC
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
steps to reproduce bug: in UG

besides giving the commands, showing the expected output in the UG will be clearer for users

screenshots below:

![Screenshot 2023-11-03 at 5.25.22 PM.png](https://raw.githubusercontent.com/janelleenqi/ped/main/files/38191e9d-c958-4e5b-a050-725da31e349b.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: janelleenqi/ped#4

**Comment by TongZhengHong** [comment] 2023-11-04 16:07
- Duplicate of #144

**Closed as completed** 2023-11-07 03:08 UTC
